### ISSUE TITLE
Chapter 4 code not working with Python 2.7

### ISSUE THREAD

**Issue by CaptSolo** [drabastomek/learningPySpark#22]
This code fragment in Chapter 4 example code does not work with Python 2.7:
```
fields = [
    *[
        typ.StructField(h[1:-1], typ.IntegerType(), True)
        for h in header.split(',')
    ]
]
```
It results in the `SyntaxError: invalid syntax` error. 

Looks like this code is Python 3.x specific. It can be fixed by removing the inner *[ ... ] brackets.

**Comment by drabastomek** [comment]
Thank you for pointing it out.

We will make changes in the next release.

**Comment by alenzhd** [comment]
if removing the inner *[ ... ] brackets is good , why use the *[ ]

**Comment by drabastomek** [comment]
That's the specifics of Python 3 syntax. All our code was tested in Anaconda Python 3.5.

**Comment by drabastomek** [comment]
The book uses Python 3 syntax.
