### ISSUE TITLE
Doesn't describ what "sc" actually is.

### ISSUE THREAD

**Issue by ResidualWolf** [drabastomek/learningPySpark#23]
data = sc.parallelize(
    [('Amber', 22), ('Alfred', 23), ('Skye',4), ('Albert', 12), 
     ('Amber', 9)])

You don't show any importing, contextualizing or anything of the sort. Came here after buying the book and looking to actually save my confusion only to be more confused.

**Comment by drabastomek** [comment]
Hi,

At the end of Chapter 1 we point to https://www.packtpub.com/sites/default/files/downloads/InstallingSpark.pdf for installation instructions of Spark and related packages. 

The doc outlines steps of installing and configuring Jupyter to automatically start when `pyspark` command is issued. When Jupyter notebook opens, SparkContext, SqlContext and SparkSession are getting started automatically.

Apologies, this should have been clearer.

**Comment by ResidualWolf** [comment]
Wow. I am very surprised. I would expect a book to put publish this. The
point of a book is to have information that is readable and concise all in
a single place.

This seems more like a reference manual for other reference manuals. Please
put additional effort to teach. I think you have a lot more knowledge to
offer and not having it at a reader's fingertips defeats the purpose. I
read this on my commute... but hasn't been helpful :/

**Comment by drabastomek** [comment]
As I wrote before, it was explained in the bonus chapter.

From Summary to Chapter 1 "(...), however, please, check the link http://www.tomdrabas.com/ site/book for the Bonus Chapter 1 where we outline instructions on how to install Spark locally on your machine (unless you already have it installed). Here's a direct link to the manual: https://www.packtpub.com/sites/default/files/ downloads/InstallingSpark.pdf."

Offloading the bonus chapter made more sense so we could update it more frequently. 

We will put your comments in the errata and in the 2nd edition, and will start a FAQ.
